### ISSUE TITLE
"Crash when loading config"

### ISSUE THREAD

**Issue by Darkmega18** [SteveKunG/YouTubeChat#4]
The instructions say to copy all thats in the credentials json into the config in game. but when I open it from the forge mod menu, it opens the actual config in notepad++. so I just paste it in between the two quotation marks for the json and save it.

But upon reloading the game or the config being read while in game it promptly crashes with this error:
[crash-2021-07-15_22.45.43-client.txt](https://github.com/SteveKunG/YouTubeChat/files/6823149/crash-2021-07-15_22.45.43-client.txt)

I'm not sure if I'm missing something glaringly obvious or if it's broken or not willing to work for my current installation.

**Comment by SteveKunG** [comment]
I recommended this mod "Configured" to edit your credentials config from in-game. Since forge doesn't do their important sh*t.
https://www.curseforge.com/minecraft/mc-mods/configured

![image](https://user-images.githubusercontent.com/6128413/143082575-149d717c-5e0b-4cbd-b2d8-f1acd8beb001.png)
